[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`
---

# Tyr\-Br

## Content
> leftSide=`true`


### GUI

### Maps

### Ores
> topicLinkUID=`18A8411872EA`


### Enemies

#### Droptables

### Objects

#### Items

### Animations

### Music / sound

### Player factions

#### Building

#### Fort

### Currency

#### Gold \(generic\)

#### player economy

## Mechanics

### Networking

#### TCP socket IO

##### Login,

###### Chat

###### Password manaegement

####### Gitignore and hashing

#### Server

##### Build server

###### Run from school computer

#### Distribute launcher

#### Network scope, me and friends or many people

#### Profit, microtransactions?

### Map
> fillColor=`#00FF00`


#### Map Constructor
> fillColor=`#FF6400`


##### Procedural maps
> fillColor=`#FF2B00`


#### Map file format decision
> fillColor=`#FFC800`


##### GameObjectFactories
> fillColor=`#FFC800`


#### Map memory fix
> fillColor=`#00FF00`,mmd.emoticon=`accept_button`


#### Camera, and camera movement

#### Map Depth

##### Map depth color

#### Map look differentiation

### Inventory
> fillColor=`#00FF00`


#### Inventory grid
> fillColor=`#00FF00`


##### Player inventory

###### Dragability

###### Item constucting

####### Item descriptions

####### Item usability

####### Item shop, sell and buy items 

##### J buttons\`?

### Combat

#### Enemies

##### Enemy class

#### Combat mechanics

##### Player combat properties

#### Death

##### Perma death

##### Respawn

### Mining
> fillColor=`#00FF00`


#### Ores class
- TOPIC
<pre>18A8411872EA</pre>

##### Mining mechanic

###### Inventory mechanic

###### Prototype mine ore on collision\. Have a set chance for the ore to drop

### Code

#### JavaDocs

#### Optimization

#### Organization

### Player movement

#### Movement cooldown, maybe stamina

### Religion

#### Jelous gods

## Plot
> leftSide=`true`


### Worlds

### Enemies

### Main character is TYR

#### No arm plot

### Set after apocalypse

#### remains

#### after world war 4 we fight again with medival weapons

### babel tower, gods got jelous, interviened

## End goal

### MMORPG?
